// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RTSec.Kryptonian.Infrastructure.Data;

#nullable disable

namespace RTSec.Kryptonian.Infrastructure.Migrations
{
    [DbContext(typeof(KryptonianDbContext))]
    [Migration("20251210234203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.CaBackend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, object>>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ca_backends", (string)null);
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_pem");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EstProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("est_profile_id");

                    b.Property<string>("IssuerDn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("issuer_dn");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectDn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subject_dn");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("thumbprint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EstProfileId");

                    b.HasIndex("NotAfter");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.EnrollmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("IssuedCertificateId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_certificate_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("RequestorIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("requestor_ip_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectDn")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subject_dn");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IssuedCertificateId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.ToTable("enrollment_events", (string)null);
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.EstProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<string>>("AllowedKeyUsages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_key_usages");

                    b.Property<Guid>("CaBackendId")
                        .HasColumnType("uuid")
                        .HasColumnName("ca_backend_id");

                    b.Property<string>("CertificateTemplate")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("certificate_template");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("Hostnames")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hostnames");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PathPrefix")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("path_prefix");

                    b.Property<bool>("RequireClientCertificate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("require_client_certificate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ValidityDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(365)
                        .HasColumnName("validity_days");

                    b.HasKey("Id");

                    b.HasIndex("CaBackendId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PathPrefix", "Hostnames")
                        .HasDatabaseName("ix_est_profiles_path_hostnames");

                    b.ToTable("est_profiles", (string)null);
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("RTSec.Kryptonian.Domain.Entities.EstProfile", "EstProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("EstProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstProfile");
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.EnrollmentEvent", b =>
                {
                    b.HasOne("RTSec.Kryptonian.Domain.Entities.Certificate", "IssuedCertificate")
                        .WithMany()
                        .HasForeignKey("IssuedCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RTSec.Kryptonian.Domain.Entities.EstProfile", "Profile")
                        .WithMany("EnrollmentEvents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssuedCertificate");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.EstProfile", b =>
                {
                    b.HasOne("RTSec.Kryptonian.Domain.Entities.CaBackend", "CaBackend")
                        .WithMany("EstProfiles")
                        .HasForeignKey("CaBackendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaBackend");
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.CaBackend", b =>
                {
                    b.Navigation("EstProfiles");
                });

            modelBuilder.Entity("RTSec.Kryptonian.Domain.Entities.EstProfile", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("EnrollmentEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
